---
- hosts: all
  gather_facts: false
  roles:

  # osx config
  - role: cask_package
    package_name: asepsis
  - role: dashboard
    disabled: YES

  # fonts
  - role: cask_package
    tap: caskroom/fonts
    package_name: font-source-code-pro
  - role: cask_package
    tap: caskroom/fonts
    package_name: font-sauce-code-powerline

  # cli
  # shell tooling
  - role: legit
  - role: hub
  - role: brew_package
    package_name: vim
  ## languages
  - role: brew_package
    package_name: node
  - role: rbenv
  - role: npm_package
    package_name: grunt
  - role: npm_package
    package_name: bower
  - role: cask_package
    package_name: java
  - role: brew_package
    package_name: android-sdk
  ## databases
  - role: cask_package
    package_name: postgres
  - role: brew_package
    package_name: redis
  - role: brew_package
    package_name: elasticsearch
  ## deployment
  - role: brew_package
    package_name: heroku-toolbelt
  # - role: brew_package
  #   package_name: ansible # Hey ! Already there !

  # gui
  ## text editors
  - role: cask_package
    package_name: textmate
  - role: cask_package
    package_name: macvim
  ## general
  - role: cask_package
    package_name: iterm2
  - role: cask_package
    package_name: firefox
  - role: cask_package
    package_name: chromium
  - role: cask_package
    package_name: dropbox
  - role: cask_package
    package_name: 1password
  - role: cask_package
    package_name: apptrap
  - role: cask_package
    package_name: alfred
  - role: cask_package
    package_name: skype
  - role: cask_package
    package_name: slack
  - role: brew_package
    package_name: htop
  - role: brew_package
    package_name: ack

 ## entertainment
  - role: cask_package
    package_name: spotify
  - role: cask_package
    package_name: vlc
