---
# vars file for base
brew_taps:
  - ['nviennot/tmate']

cask_taps:
  - []

brew_packages_bootstrap:
  - ['mutt', 'profanity', 'tmate', 'urlview', 'msmtp', 'notmuch', 'offlineimap', 'sshuttle', 'links', 'hub', 'phantomjs']

cask_packages_bootstrap:
  - ['textmate', 'macvim', 'iterm2', 'firefox', 'google-chrome', 'dropbox', '1password', 'apptrap', 'skype', 'slack', 'genymotion', 'vlc', 'jitsi', 'intellij-idea-ce', 'vagrant', 'libreoffice', 'virtualbox', 'limechat', 'deluge', 'phantomjs', 'gpgtools', 'kindle', 'genymotion', 'unrarx', 'flash', 'ynab', 'atom']

npm_global_packages:
  - []
