---
# vars file for base
brew_taps:
  - []

cask_taps:
  - []

brew_packages_bootstrap:
  - ['mutt', 'profanity', 'gpg2']

cask_packages_bootstrap:
  - ['textmate', 'macvim', 'iterm2', 'firefox', 'chromium', 'dropbox', '1password', 'apptrap', 'skype', 'slack', 'spotify', 'vlc', 'jitsi', 'intellij-idea-ce', 'vagrant', 'libreoffice', 'virtualbox', 'limechat', 'deluge']

npm_global_packages:
  - []
