---
# vars file for base
brew_taps:
  - ['gapple/services']

cask_taps:
  - ['caskroom/fonts']

brew_packages_bootstrap:
  - ['vim', 'node', 'android-sdk', 'redis', 'elasticsearch', 'postgres', 'heroku-toolbelt', 'htop', 'ack', 'tarsnap', 'fish', 'tree', 'peco', 'ag']

cask_packages_bootstrap:
  - ['asepsis', 'font-source-code-pro', 'font-sauce-code-powerline', 'java']

npm_global_packages:
  - ['grunt', 'grunt-cli', 'bower']

fish_path: /usr/local/bin/fish