---

- name: tap_brew
  homebrew_tap: tap={{ item }} state=present
  with_flattened:
    - brew_taps

- name: cask_brew
  homebrew_tap: tap={{ item }} state=present
  with_flattened:
    - cask_taps

- name: install_brew_packages
  homebrew: name={{ item }} state=installed
  with_flattened:
    - brew_packages_bootstrap

- name: install_brew_packages
  homebrew_cask: name={{ item }} state=present
  with_flattened:
    - cask_packages_bootstrap

- name: install_npm_packages
  npm: name={{ item }} global=yes state=present
  with_flattened:
    - npm_global_packages

- name: add_fish_to_shells
  lineinfile: dest=/etc/shells line={{ fish_path }} state=present
  sudo: yes
  sudo_user: "{{ default_user }}"

- name: current_shell
  shell: echo $SHELL | grep -c fish || true
  register: fish_shell

- name: switch_to_fish
  shell: chsh -s {{ fish_path }} {{ default_user }}
  when: fish_shell.stdout != "1"